- .eslintignore
- .npmignore
- package.json
- src/DependencyInjection/DependencyInjection.class.js
- src/Model/SQS/Message.model.js
- src/Service/SQS.service.js
- src/index.js
- tests/unit/Model/SQS/Message.model.js
- yarn.lock
Adds SQS service and dependencies
> Add SQS Service

- package.json
- src/Service/SQS.service.js
Add the queue that a message was published to as part of the resolution for SQS publish
> Add queue name to publish response from SQS

- package.json
- src/Service/Logger.service.js
- yarn.lock
> Add raven client

- .eslintrc
- package.json
- src/Chaos/PromisifiedDelay.js
- src/Wrapper/LambdaWrapper.js
Adds delays that can be introduced by the chaos module
> Add chaos delays

- .circleci/config.yml
- README.md
- package.json
- yarn.lock
> #11 add semantic release via circle

- package.json
- src/Config/Dependencies.js
- src/Service/SQS.service.js
- src/Service/Timer.service.js
- src/Wrapper/LambdaWrapper.js
- yarn.lock
Adds TIminig service and iopipe timing.
> Add timing service

- src/Service/Logger.service.js
Adds error labelling to error messages
> Add error tagging to lambdas

- src/Service/Request.service.js
- yarn.lock
Fixes #25 - multipart form and aws events support in request service
> Fixes #25 - Multipart form and aws events support

- src/Service/Logger.service.js
> #30 Logger DI change

- src/Service/Request.service.js
Adds labelling to request validation failure
> Add label to request validation

- src/Model/SQS/MarketingPreference.constraints.json
- src/Model/SQS/MarketingPreference.model.js
- tests/unit/Model/SQS/MarketingPreferences.model.js
Modified Marketing preference model and constraints to handle nullable and conditionally required fields
> Update marketing pref model

- src/Model/SQS/MarketingPreference.constraints.json
- src/Model/SQS/MarketingPreference.model.js
- tests/unit/Model/SQS/MarketingPreferences.model.js
fix: more marketing prefs custom validation
> fix: more marketing prefs custom validation

- src/Model/SQS/MarketingPreference.constraints.json
- src/Model/SQS/MarketingPreference.model.js
- tests/unit/Model/SQS/MarketingPreferences.model.js
fix: updated marketing preferences model
Fixes #36
> fix: updated marketing preferences model

- src/Model/SQS/MarketingPreference.model.js
- tests/unit/Model/SQS/MarketingPreferences.model.js
fix: property 'trim' of null field value
> fix: property 'trim' of null field value

- src/Model/SQS/MarketingPreference.model.js
- tests/unit/Model/SQS/MarketingPreferences.model.js
fix: marketing preferences model issues
> fix: marketing preferences model issues

- src/Model/SQS/MarketingPreference.model.js
fix: added handle for payment first and last name fields
> fix: added handle for payment first and last name fields

- package.json
- src/Service/Request.service.js
- src/Wrapper/LambdaWrapper.js
- tests/unit/Service/Request.service.js
- yarn.lock
To enable us to faster track down errors to device types and browsers
> Record browser and device to iopipe

- src/Model/SQS/MarketingPreference.model.js
- tests/unit/Model/SQS/MarketingPreferences.model.js
fix: added action id to marketing prefs
> fix: added action id to marketing prefs

- src/Model/SQS/MarketingPreference.model.js
- tests/unit/Model/SQS/MarketingPreferences.model.js
fix: renamed actionId to transactionId for marketing prefs
> fix: renamed actionId to transactionId for marketing prefs

- package.json
- yarn.lock
fix: bumped vulnerable dependencies
> fix: bumped vulnerable dependencies

- src/Model/SQS/MarketingPreference.model.js
- tests/unit/Model/SQS/MarketingPreferences.model.js
fix: email permission validations
> fix: email permission validations

- src/Model/SQS/MarketingPreference.model.js
- tests/unit/Model/SQS/MarketingPreferences.model.js
fix: updated validation when email permission is no
> fix: updated validation when email permission is no

- .snyk
- package.json
- yarn.lock
fix: useragent dependency vulnerability
- Ignore useragent dependency in synk until patch is available
> fix: useragent dependency vulnerability

- package.json
- src/Service/Logger.service.js
- src/Service/Timer.service.js
- src/Wrapper/LambdaWrapper.js
- yarn.lock
- Fix iopipe warnings thrown due to calling iopipe methods after lambda invocation (after losing context).
> Fix iopipe

- package.json
- src/Service/Logger.service.js
- src/Service/Timer.service.js
- src/Wrapper/LambdaWrapper.js
- yarn.lock
Removes IOPipe from wrapper before 15th December cut off
> Remove IOPipe from wrapper

- src/Service/Request.service.js
- tests/unit/Service/Request.service.js
> fix: Catch error when headers are null.

- src/DependencyInjection/DependencyAware.class.js
- src/DependencyInjection/DependencyInjection.class.js
- src/Service/Logger.service.js
- src/Service/SQS.service.js
- tests/unit/DependencyInjection/DependencyInjection.class.test.js
- tests/unit/Service/Logger.service.test.js
> fix: prettyprint logs if process.env.USE_SERVERLESS_OFFLINE

- .github/workflows/git-checks.yml
> ci: Add fixup commits blocker for PRs

- src/Wrapper/LambdaWrapper.js
- yarn.lock
- It should allow lambda to throw error, so that SQS or similar service can detect failure
Fixes https://comicrelief.atlassian.net/browse/ENG-90
> fix: lambda error handling

- .eslintignore
- .eslintrc
- .eslintrc.yml
- package.json
- src/DependencyInjection/DependencyAware.class.js
- src/DependencyInjection/DependencyInjection.class.js
- src/Model/CloudEvent.model.js
- src/Model/Model.model.js
- src/Model/Response.model.js
- src/Model/SQS/MarketingPreference.model.js
- src/Model/SQS/Message.model.js
- src/Model/Status.model.js
- src/Service/Logger.service.js
- src/Service/Request.service.js
- src/Service/SQS.service.js
- src/Service/Timer.service.js
- src/Wrapper/LambdaTermination.js
- src/Wrapper/LambdaWrapper.js
- src/Wrapper/PromisifiedDelay.js
- tests/.eslintrc
- tests/.eslintrc.yml
- tests/unit/Service/Logger.service.test.js
- tests/unit/Service/Request.service.test.js
- tests/unit/Wrapper/LambdaWrapper.test.js
- yarn.lock
- The JSdoc plugin is activated
- The codebase lints successfully
See:
- [ENG-33]
- [ENG-112]
[ENG-33]: https://comicrelief.atlassian.net/browse/ENG-33
[ENG-112]: https://comicrelief.atlassian.net/browse/ENG-112
> chore: Enable JSdoc plugin for `lambda-wrapper`

- .github/workflows/main.yml
> ci: Update publishing token, correctly this time

- README.md
Adds a bit more visibility for the new beta releases. Any thoughts on what it should say?
> docs: Announce the v2 beta at top of readme

- docs/services/LoggerService.md
- src/services/LoggerService.ts
> docs: Remove remaining references to Epsagon
