src/Model/SQS/MarketingPreference.model.js, tests/unit/Model/SQS/MarketingPreferences.model.js
fix: #38 - nullable address fields in marketing preference model
=> fix: nullable address fields in marketing preference model

src/Wrapper/LambdaWrapper.js
This happens locally during development.
=> Fix timeouts thrown even when a response is already returned

package.json, tests/unit/Wrapper/LambdaWrapper.js, yarn.lock
They are not really required if we removed `async` from unit tests and they were forcing implementing apps to add @babel/runtime to the dependencies.
=> fix: Removed babel deps added in 1.1.2

package.json, yarn.lock
- aws-sdk is now a peer dependency.
- snyk is now a dev dependency.
While the modules will be removed in the webpack bundle, they will be packaged together by yarn because of the generated `yarn.lock` that comes with the current `package.json`, adding 100MB+ worth of files to the uploaded serverless zip.
Closes #91
=> Updated dependencies.

src/Service/SQS.service.js
The full qualified queue URL is not included in the timer id for each timer where the queue URL is available.
Closes #76
=> fix: Add more descriptive names to SQS timers (#76)

src/Model/Response.model.js, tests/unit/Model/Response.model.test.js
Currently we generate response objects by using:
>>> const response = new ResponseModel(body, code, message);
>>> // some processing
>>> return response.generate()
However a lot of times no processing is actually performed and we create a ResponseModel object just to use its `generate` method.
A static method named `generate` has been added to compress response model creation & response generation into one line:
>>> return ResponseModel.generate(body, code, message);
Apart from moving the number of lines from 2 to 1 in a lot of places the static method is more terse and easier to understand. More over we can to without an intermediate "response" object, freeing the name for API responses performed in the Lambda.
=> fix: Add ResponseModel.generate shortcut

src/Wrapper/LambdaWrapper.js, tests/unit/Wrapper/LambdaWrapper.test.js
No point in logging an error for a planned failure (4xx).
Closes #103
=> fix: 4xx error should log INFO and not ERROR

src/Service/Request.service.js, tests/unit/Service/Request.service.test.js
Adds two new methods to `RequestService`:
- `getAllHeaders()`: shortcut for `request.getContainer().getEvent().headers`
- `getHeader(name, default='')`: get a header value using a case-insensitive search
Some of the existing code can then be significantly improved using `getHeader`.
=> feat: Add getters for headers

src/DependencyInjection/DependencyAware.class.js, src/DependencyInjection/DependencyInjection.class.js, tests/unit/DependencyInjection/DependencyAware.class.test.js, tests/unit/DependencyInjection/DependencyInjection.class.test.js
Currently we need to import the `DEFINITIONS` from `src/config/Configuration` and this can lead to circular imports. There isn't really a need for that as we `di` contains `configuration`, which in turns contains `DEFINITIONS`.
A getter will simplify how we access to those constants.
See:
- [ENG-48]
[ENG-48]: https://comicrelief.atlassian.net/browse/ENG-48
=> fix: Implement getter for `CONFIGURATION.DEFINITIONS`

src/Wrapper/LambdaWrapper.js, tests/lib/mocks.js, tests/unit/Wrapper/LambdaWrapper.test.js, tests/unit/Wrapper/__snapshots__/LambdaWrapper.test.js.snap
Our error handling on Lambda Wrapper checks whether `error.code` is defined and below 500 (meaning a 4xx error). While this makes sense in most uses cases, as we are unlikely to be interested at all in 4xx errors, there are scenarios where we are forced to throw a 4xx and we might be interested in logging in.
This is correlated to [ENG-110].
Error handling will check whether `error.raiseOnEpsagon` is defined and true. This condition will override the error code check, allowing us to put some dynamic logic on whether an error should be logged on Epsagon regardless of code. For example, we might not care about the first time we get an HTTP 417 and just retry, but be alarmed once it gets on the DLQ.
See:
- [ENG-110]
- [ENG-111]
[ENG-110]: https://comicrelief.atlassian.net/browse/ENG-110 …
=> fix: Allow HTTP4xx to be logged on Epsagon

src/Wrapper/LambdaWrapper.js, tests/unit/Wrapper/LambdaWrapper.test.js, tests/unit/Wrapper/__snapshots__/LambdaWrapper.test.js.snap
Axios errors are really verbose and local development terminals get spammed, especially if more than one test fail because of HTTP errors.
While handling an error, lambda wrapper should recognise axios errors and trim down the information to the request config, response.status and response.data
See:
- [ENG-115]
[ENG-115]: https://comicrelief.atlassian.net/browse/ENG-115
=> fix: Improve error logging for axios errors

src/Service/Logger.service.js, src/Wrapper/LambdaWrapper.js, tests/unit/Service/Logger.service.test.js, tests/unit/Service/__snapshots__/Logger.service.test.js.snap, tests/unit/Wrapper/LambdaWrapper.test.js, tests/unit/Wrapper/__snapshots__/LambdaWrapper.test.js.snap
Services might catch the error and just log it, so it would not be
propagated at top level and pretty-printed. Extending LoggerService
takes care of those use cases.
=> fix: Move axios error processing in LoggerService

src/Service/Logger.service.js, tests/unit/Service/Logger.service.test.js
I have been thinking on how logger.error gets in the way of testing. I believe failures should be as noisy as they can be, and also that they should be tested.
When it comes to test a function failure that has the side effect of calling logger.error what we really want to observe is some kind of error handling (i.e. the function forces the lambda to return a form of HTTP 4xx). In production usage, we might want to trigger logger.error. This is even more true when the lambda is triggered by SQS. The reason is that we want to log the error to Epsagon while not necessarily fail the function (especially if we are processing several messages in one call).
Enter feature tests. The behaviour above is all good for production, but when running integration tests it spams Epsagon with false …
=> feat: Define logger.warning function

package.json, src/Service/BaseConfig.service.js, src/index.js, tests/unit/Service/BaseConfig.service.test.js, tests/unit/Service/__snapshots__/BaseConfig.service.test.js.snap, yarn.lock
Instead of reproducing the service status get and service status set logic across several services, Lambda Wrapper will define a Status service that handles these two operations for us.
See:
- [ENG-153]
- [ENG-164]
[ENG-153]: https://comicrelief.atlassian.net/browse/ENG-153
[ENG-164]: https://comicrelief.atlassian.net/browse/ENG-164
=> feat: Define lambda-wrapper status helper

package.json, src/Model/CloudEvent.model.js, src/Model/SQS/MarketingPreference.model.js, src/Service/Logger.service.js, src/Service/Request.service.js, src/Service/SQS.service.js, src/Service/Timer.service.js, src/Wrapper/LambdaWrapper.js, tests/unit/DependencyInjection/DependencyAware.class.test.js, tests/unit/DependencyInjection/DependencyInjection.class.test.js, tests/unit/Model/SQS/MarketingPreferences.model.test.js, tests/unit/Service/BaseConfig.service.test.js, tests/unit/Service/Logger.service.test.js, tests/unit/Service/Request.service.test.js, tests/unit/Wrapper/LambdaWrapper.test.js, yarn.lock
Upgrading to @comicrelief/eslint-config lets us lint imports, sorting
them in logical groups.
=> chore: Lint imports

src/Service/Logger.service.js, tests/unit/Service/Logger.service.test.js, tests/unit/Service/__snapshots__/Logger.service.test.js.snap
Sometimes we want to log an object, i.e. "Processing: X", but there is a
lot of boilerplate involved each time, as we need to JSON.stringify the
object and put the result in a template string.
The `.object` method will cut the boilerplate for us.
=> fix: Add ability to log objects easily

src/Service/BaseConfig.service.js, tests/unit/Service/BaseConfig.service.test.js
In the `aws-sdk` if you don't pass a callback to the operation AND you
don't await the `.promise()` the operation is not really executed and
fails silently.
=> fix(BaseConfig): Await the putObject request

src/Service/Request.service.js, tests/unit/Service/Request.service.test.js, tests/unit/Service/__snapshots__/Request.service.test.js.snap
Currently LambdaWrapper only supports HTTP GET and HTTP POST. This works out fine but we lose some semantic value (for example with PATCH and DELETE).
See:
- [ENG-169]
[ENG-169]: https://comicrelief.atlassian.net/browse/ENG-169
=> fix: Support additional HTTP methods

src/Service/BaseConfig.service.js, tests/unit/Service/BaseConfig.service.test.js, tests/unit/Service/__snapshots__/BaseConfig.service.test.js.snap
It is a common task to health check an application at start up and force an early failure. The health check logic should be based on LambdaWrapper and extended in each application.
See:
- [ENG-210]
[ENG-210]: https://comicrelief.atlassian.net/browse/ENG-210
=> feat: Implement HealthCheck functionality

src/Service/BaseConfig.service.js
Only prize platform uses them and its models are correct.
=> fix: Correct spelling of BaseConfig states

src/Wrapper/LambdaWrapper.js, tests/lib/mocks.js, tests/unit/Wrapper/LambdaWrapper.test.js, tests/unit/Wrapper/__snapshots__/LambdaWrapper.test.js.snap
For SQS triggered functions, we throw unhandled exceptions in order to force SQS to requeue the message, so it can be retried according to the related SQS policy.
However, unhandled exceptions break Epsagon's own lambda wrapper, resulting in missing Epsagon traces.
To solve the issue, we can return error objects (i.e. `obj instanceof Error === true`) so that the lambda function completes but still counts as failed.
See:
- [ENG-240]
[ENG-240]: https://comicrelief.atlassian.net/browse/ENG-240
=> fix: Avoid throwing unhandled exceptions to preserve Epsagon traces

package.json, src/Service/SQS.service.js, tests/unit/Service/SQS.service.test.js, yarn.lock
When using `serverless-offline`, LambdaWrapper performs an HTTP Request trying to pass its content to a message queue instance running on localhost. We can intercept the HTTP Request, but it is problematic to code and to think about.
Serverless Offline allows us to trigger lambdas via the AWS SDK. We can map lambdas to queues via an environment variable and trigger functions directly. This has the added benefit of allowing any number of triggers (i.e. one function that queues 10 messages) and to simplify how we test those functions locally.
See:
- [ENG-245]
[ENG-245]: https://comicrelief.atlassian.net/browse/ENG-245
=> feat: Call SQS triggered lambdas directly when using serverless-offline

src/Service/SQS.service.js
Fixes [ENG-316]
Next would be updating supporter events to use the latest lambda wrapper.
[ENG-316]: https://comicrelief.atlassian.net/browse/ENG-316
=> fix: limit sqs timeout to be able to retry in case of failure

README.md, src/DependencyInjection/DependencyInjection.class.js, src/Service/SQS.service.js, tests/unit/Service/SQS.service.test.js
This PR makes offline SQS behaviour configurable using the `LAMBDA_WRAPPER_OFFLINE_SQS_MODE` environment variable.
This will allow end-to-end tests that really do need to publish to SQS to run in serverless-offline, and also provides a way to recreate the old lambda-wrapper behaviour of sending to Localstack.
Discussion around the names of options is welcome – the current names may not be the clearest! In particular, `LAMBDA_WRAPPER_OFFLINE_SQS_MODE=none` could be interpretted as "there will be no SQS messages sent when offline" rather than the intended "there is no special redirection of SQS messages when offline".
=> feat: Configurable SQS offline mode

src/Service/SQS.service.js, tests/unit/Service/SQS.service.test.js
Fixes [ENG-356].
Failure to publish a message should be handled by the caller, as it may be on their critical path.
[ENG-356]: https://comicrelief.atlassian.net/browse/ENG-356
=> fix: Remove try-catch from SQSService.publish

src/Service/SQS.service.js, src/index.js, tests/unit/Service/SQS.service.test.js, tests/unit/Service/__snapshots__/SQS.service.test.js.snap
Instead of throwing, we should let the default behaviour for LambdaWrapper to catch exceptions.
Services needing to throw, should pass a `failureMode` flag
See:
- [ENG-375]
[ENG-375]: https://comicrelief.atlassian.net/browse/ENG-375
=> fix: Default SQS.publish behaviour to not throw exceptions

src/Wrapper/LambdaWrapper.js
The contact store was updated yesterday; it has scheduled tasks that don't return a value so we are getting `Cannot read property 'statusCode' of undefined` errors.
=> fix: Don't expect all lambdas to have a return value

README.md
We no longer use CircleCI to test and publish this repo.
I've replaced it with a GitHub Actions badge. See GitHub's guide here:
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
=> docs: Fix CI status badge

src/Service/Logger.service.js
As reported by Tom, Epsagon's `label()` function expects two arugments, and fails silently if only one is given.
See their docs: https://docs.epsagon.com/docs/nodejs#tagging-traces
Jira: [ENG-419]
[ENG-419]: https://comicrelief.atlassian.net/browse/ENG-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Logger.label was not labelling traces

README.md, src/Service/SQS.service.js, tests/unit/Service/SQS.service.test.js
Please refer to **#659 SQS Port as Env. Configuration** for more details.
=> feat: Allow SQS port number to be passed as environmental configuration

.github/workflows/main.yml
As you can see from the [latest attempt to publish](https://github.com/comicrelief/lambda-wrapper/runs/7948453941?check_suite_focus=true), this repo is still using the old token!
=> ci: Update publishing token

.github/workflows/main.yml
Currently config allows publishing from `master` only.
=> ci: Run publish job on `beta` branch

README.md
So that someone looking at the `beta` branch gets instructions that they can follow to install this version.
This will need reverting just before we merge `beta` into `master`.
=> docs: Show how to install the beta version

docs/services/SQSService.md, src/core/DependencyAwareClass.ts, src/core/DependencyInjection.ts, src/core/LambdaWrapper.ts, src/index.ts, src/services/SQSService.ts, tests/unit/services/SQSService.spec.ts
Dependency-aware classes can now access the type of the Lambda Wrapper config. This opens the door to using information from the config to better type some methods.
As an example, our `SQSService` has many methods that take a queue name. Previously these had to be type `string` and we relied on runtime checks to ensure valid queue names were passed in. With access to the config type, we can infer queue names from the keys of `config.sqs.queues`, so this check can now be done at compile-time, _and_ we get IntelliSense suggestions for queue names!
This is still a work in progress, although potentially useful and usable enough in its current state to release to beta. See the updated documentation for known issues.
There should be no breaking changes. All new type parameters are optional. …
=> feat: Propagate config type to dependencies

src/core/DependencyInjection.ts
Hidden because it was on a line join.
=> fix: Add missing space in DI error message

src/core/LambdaWrapper.ts
The current type of `LambdaWrapper#wrap` requires handlers to return a `Promise`. We should support synchronous handlers too.
No implementation change is required – they're already supported, just disallowed by the type system.
Jira: [ENG-2732]
[ENG-2732]: https://comicrelief.atlassian.net/browse/ENG-2732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Allow synchronous handlers

README.md, package.json, src/core/LambdaWrapper.ts, src/services/LoggerService.ts, tests/unit/core/LambdaWrapper.spec.ts, yarn.lock
Epsagon is no longer operating. They took down their website on 3 October and backend services have been gradually removed, and since 10 October any service still making requests to Espagon servers faces delays and Lambda timeouts.
We have now migrated to [Lumigo](https://lumigo.io/). Their platform supports [auto-tracing](https://docs.lumigo.io/docs/serverless-applications#automatic-instrumentation), allowing us to begin monitoring without deploying updates to Lambda Wrapper, however we are missing our metrics and labels which correspond to [Execution Tags](https://docs.lumigo.io/docs/execution-tags) in Lumigo.
This PR makes the change to wrap handlers with Lumigo's tracer, and updates our logger to use Execution Tags for metrics and labels. To enable Lumigo tracing and tags, set …
=> feat: Replace Epsagon with Lumigo

src/core/DependencyInjection.ts, tests/mocks/dependencies.ts, tests/mocks/dependencies2.ts, tests/unit/core/DependencyInjection.spec.ts
Adds validation to check that all dependencies have a unique name.
This follows on from [a discussion](https://github.com/comicrelief/serverless-payments/pull/614#discussion_r1332757352) with @zhibek about why we need to turn off webpack's minification optimisation. TL;DR two dependency classes can be minified to the same one-letter name, and since dependencies are keyed by class name, this causes nasty runtime errors.
Lambda Wrapper will now be able to detect this situation and suggest turning off minification, linking to the [readme note](https://github.com/comicrelief/lambda-wrapper/tree/beta#notes) of how to do this for webpack.
As part of this, dependency classes will be deduplicated before being instantiated. If a dependency is specified several times (unlikely but possible) it will …
=> feat: Throw if there are conflicting dependency names

docs/migration/v2.md, docs/services/RequestService.md, src/services/RequestService.ts, tests/unit/services/RequestService.spec.ts
This is consistent with many other libraries (e.g. http, axios) and makes it easier to work with HTTP headers.
The HTTP protocol states that header names are case-insensitive, so currently when using `getAllHeaders` you must worry about the case of the header name:
```js
const headers = request.getAllHeaders();
const contentType = headers['Content-Type'] || headers['content-type'];
// but what if someone sends us `Content-type`?
```
The existing `getHeader` method solved this by doing a case-insensitive search of all keys. Now, you can also safely use the lowercase key:
```js
const headers = request.getAllHeaders();
const contentType = headers['content-type'];
```
Jira: [ENG-2735]
BREAKING CHANGE: Header keys returned by `getAllHeaders` are converted to lowercase. Accessing headers …
=> feat: Return lowercase header keys from `getAllHeaders`

src/models/SQSMessageModel.ts
Further work to make `SQSMessageModel` more type-safe.
- Properties that have only a getter (no setter) are made readonly
- `body` type changed from `string` (incorrect) to `unknown`
Jira: [ENG-2733]
[ENG-2733]: https://comicrelief.atlassian.net/browse/ENG-2733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Improve `SQSMessageModel` types

docs/migration/v2.md, src/models/SQSMessageModel.ts
Change the name of the class to match the name exported from the package index.
This should not be a breaking change because the class is the default export of its module. Just in case there is some contrived case that depends on the class's `name` attribute, we'll include this in the v2.0.0 major release.
Jira: [ENG-2733]
[ENG-2733]: https://comicrelief.atlassian.net/browse/ENG-2733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: Rename SQS message model class

src/models/SQSMessageModel.ts
The main point I wanted to add here is that this model is for _received_ messages. I've also added a bit of explanation about its intended use with `SQSService`.
Jira: [ENG-2733]
[ENG-2733]: https://comicrelief.atlassian.net/browse/ENG-2733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Add instructions to `SQSMessageModel`

docs/migration/v2.md, src/services/SQSService.ts, tests/unit/services/SQSService.spec.ts
Currently, sending an SQS message using `SQSService` does not throw an error by default. This has caught us out a couple of times where we were expecting a failure. The `failureMode` parameter was added to opt in to throwing errors, to avoid introducing a breaking change in v1.
In v2 we'll throw errors by default, and you'll have to opt _out_ of this behaviour.
BREAKING CHANGE: `SQSService#publish` throws by default instead of handling errors. To maintain old behaviour, you can pass `"catch"` in the `failureMode` parameter.
=> feat: Throw by default from failed SQS publish

README.md, docs/migration/v2.md, src/core/LambdaWrapper.ts, tests/unit/core/LambdaWrapper.spec.ts
Adds some basic config validation at runtime, which will help avoid problems in projects that are not using TypeScript. In particular, we will now throw an error if a dependency does not extend `DependencyAwareClass`.
Not marking this as a separate breaking change because bad configs will already cause compile-time errors in TypeScript.
Jira: [ENG-3207]
[ENG-3207]: https://comicrelief.atlassian.net/browse/ENG-3207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Runtime config validation

README.md, src/core/DependencyInjection.ts
To be merged just before #1195, so that the docs in the 2.0.0 release do not tell you to install from the beta channel.
=> docs: Remove refs to beta ahead of 2.0.0 release

.github/workflows/main.yml
Deals with this warning from GitHub Actions:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, actions/setup-node@v1, actions/cache@v2.
=> ci: Use Node 18 and upgrade actions

src/services/LoggerService.ts
Updates some old JSDoc comments to say Lumigo instead.
Jira: [ENG-3412]
[ENG-3412]: https://comicrelief.atlassian.net/browse/ENG-3412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Remove refs to Epsagon in `LoggerService`

docs/migration/v2.md, src/services/SQSService.ts, tests/unit/services/SQSService.spec.ts
The current type is `null | undefined`, which is unusable!
I've changed this to `string | null | undefined` as a non-breaking step torwards `string | undefined`, with plans to remove the `null` type in v3.
=> fix: Incorrect type for SQS `messageGroupId`

src/services/SQSService.ts
Our current offline SQS event payload contains only the message body. This is insufficient in applications where we need to inspect the metadata of received messages, and leads to `TypeError` in the consumer during testing.
This PR adds the missing fields to the event, trying to be relatively accurate. For example, the source queue ARN includes the correct queue name and AWS account ID. In terms of overall structure, an `SQSEvent` type is helpfully provided in the `@types/aws-lambda` package, which I've used to ensure our mocked event meets expectations.
Complete event samples can be found here for reference: https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html
Jira: [ENG-3437]
[ENG-3437]: https://comicrelief.atlassian.net/browse/ENG-3437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
=> fix: Pass complete SQS event to offline queue consumer

src/services/SQSService.ts
The `alai` function works using the Lambda context object to parse the invoked function name. As an acronym for AWS Lambda Account ID it is not particularly memorable or descriptive. This PR aliases the function as `getAccountIDFromContext` to make it a little more understandable.
Tests pass.
=> refactor: Alias the `alai` function

.github/workflows/main.yml
Should fix this failed run: https://github.com/comicrelief/lambda-wrapper/actions/runs/13030440453
Not clear why this job wasn't already using `actions/setup-node`, but seems that Node 20 is now the default.
Setting to Node 18 for consistency with other jobs, for now, so we can unblock that publish. We do need to migrate everything to Node 20+, but as the last publish failure demonstrated, there's an incompatibility with one of the ESLint plugins. We need to resolve this in our ESLint config before we can upgrade here.
=> ci: Pin Node version in `publish` job
